/**
 * lib/admin/pipeline/mockData.ts
 *
 * Mocked data realista para validar la UI del modulo Pipeline admin
 * mientras el backend Python no expone los endpoints reales.
 *
 * IMPORTANTE: este modulo solo se usa cuando el flag MOCK_PIPELINE=true
 * o cuando el backend devuelve 503/timeout. En produccion los endpoints
 * proxy a /admin/pipeline/* del backend Railway.
 *
 * Los datos reflejan el estado esperado durante el bulk ingest:
 *  - Sprint 1 completo: 590 plantillas curadas
 *  - Sprint 2 en progreso: 35K/60K sentencias Corte CC
 *  - Sprints 3-6 pendientes
 */

import type {
  PipelineStatusGlobal,
  SourceStats,
  InventorySummary,
  RunningJob,
  CronJob,
  PipelineLogEntry,
  SourceId,
} from './types';

const SOURCE_DISPLAY: Record<SourceId, string> = {
  corte_cc: 'Corte Constitucional',
  corte_suprema: 'Corte Suprema de Justicia',
  consejo_estado: 'Consejo de Estado',
  suin_juriscol: 'SUIN-Juriscol (normas)',
  senado: 'Secretaría del Senado',
  colombia_compra: 'Colombia Compra Eficiente',
  defensoria: 'Defensoría del Pueblo',
  icbf: 'ICBF',
  minjusticia: 'Ministerio de Justicia (SICAAC)',
  mintrabajo: 'Ministerio del Trabajo',
  ccb: 'Cámara de Comercio Bogotá',
  dian: 'DIAN (conceptos)',
  jep: 'JEP',
  datos_gov_co: 'datos.gov.co',
  hf_datasets: 'Hugging Face Datasets',
  repos_universitarios: 'Repositorios universitarios',
  diario_oficial: 'Diario Oficial',
};

const now = () => new Date().toISOString();
const minutesAgo = (n: number) => new Date(Date.now() - n * 60_000).toISOString();
const hoursAgo = (n: number) => new Date(Date.now() - n * 3600_000).toISOString();

export const MOCK_GLOBAL: PipelineStatusGlobal = {
  health: 'healthy',
  active_workers: 3,
  total_workers: 5,
  jobs_queued: 24500,
  jobs_running: 5,
  jobs_failed_last_24h: 12,
  docs_ingested_today: 8240,
  docs_ingested_last_24h: 11200,
  storage: {
    postgres_pct: 31.2,
    r2_pct: 8.4,
  },
  cost_today_usd: 4.12,
  cost_month_usd: 38.7,
};

export const MOCK_SOURCES: SourceStats[] = [
  {
    source: 'colombia_compra',
    display_name: SOURCE_DISPLAY.colombia_compra,
    total: 40,
    pending: 0,
    processing: 0,
    completed: 40,
    failed: 0,
    skipped: 0,
    pct_done: 100,
    avg_seconds_per_doc: 7.2,
    total_minutes_spent: 4.8,
    last_completed_at: hoursAgo(18),
    eta: null,
    last_error: null,
  },
  {
    source: 'defensoria',
    display_name: SOURCE_DISPLAY.defensoria,
    total: 200,
    pending: 0,
    processing: 0,
    completed: 198,
    failed: 2,
    skipped: 0,
    pct_done: 99,
    avg_seconds_per_doc: 9.1,
    total_minutes_spent: 30.0,
    last_completed_at: hoursAgo(15),
    eta: null,
    last_error: 'http_404 en cartilla_violencia_intrafamiliar.pdf',
  },
  {
    source: 'icbf',
    display_name: SOURCE_DISPLAY.icbf,
    total: 150,
    pending: 0,
    processing: 0,
    completed: 150,
    failed: 0,
    skipped: 0,
    pct_done: 100,
    avg_seconds_per_doc: 7.8,
    total_minutes_spent: 19.5,
    last_completed_at: hoursAgo(14),
    eta: null,
    last_error: null,
  },
  {
    source: 'minjusticia',
    display_name: SOURCE_DISPLAY.minjusticia,
    total: 50,
    pending: 0,
    processing: 0,
    completed: 50,
    failed: 0,
    skipped: 0,
    pct_done: 100,
    avg_seconds_per_doc: 6.4,
    total_minutes_spent: 5.3,
    last_completed_at: hoursAgo(14),
    eta: null,
    last_error: null,
  },
  {
    source: 'mintrabajo',
    display_name: SOURCE_DISPLAY.mintrabajo,
    total: 50,
    pending: 0,
    processing: 0,
    completed: 50,
    failed: 0,
    skipped: 0,
    pct_done: 100,
    avg_seconds_per_doc: 6.1,
    total_minutes_spent: 5.1,
    last_completed_at: hoursAgo(13),
    eta: null,
    last_error: null,
  },
  {
    source: 'ccb',
    display_name: SOURCE_DISPLAY.ccb,
    total: 100,
    pending: 0,
    processing: 0,
    completed: 100,
    failed: 0,
    skipped: 0,
    pct_done: 100,
    avg_seconds_per_doc: 12.3,
    total_minutes_spent: 20.5,
    last_completed_at: hoursAgo(12),
    eta: null,
    last_error: null,
  },
  {
    source: 'suin_juriscol',
    display_name: SOURCE_DISPLAY.suin_juriscol,
    total: 87437,
    pending: 0,
    processing: 0,
    completed: 87434,
    failed: 3,
    skipped: 0,
    pct_done: 100,
    avg_seconds_per_doc: 0.12,
    total_minutes_spent: 175.0,
    last_completed_at: hoursAgo(8),
    eta: null,
    last_error: null,
  },
  {
    source: 'senado',
    display_name: SOURCE_DISPLAY.senado,
    total: 5000,
    pending: 0,
    processing: 0,
    completed: 4987,
    failed: 13,
    skipped: 0,
    pct_done: 99.7,
    avg_seconds_per_doc: 2.1,
    total_minutes_spent: 175.0,
    last_completed_at: hoursAgo(6),
    eta: null,
    last_error: 'parse_error en Ley 1098 de 2006',
  },
  {
    source: 'corte_cc',
    display_name: SOURCE_DISPLAY.corte_cc,
    total: 60000,
    pending: 24500,
    processing: 5,
    completed: 35200,
    failed: 295,
    skipped: 0,
    pct_done: 58.7,
    avg_seconds_per_doc: 0.85,
    total_minutes_spent: 498.0,
    last_completed_at: minutesAgo(2),
    eta: new Date(Date.now() + 1.8 * 3600_000).toISOString(),
    last_error: 'soft_404 en T-999-26',
  },
  {
    source: 'corte_suprema',
    display_name: SOURCE_DISPLAY.corte_suprema,
    total: 100000,
    pending: 100000,
    processing: 0,
    completed: 0,
    failed: 0,
    skipped: 0,
    pct_done: 0,
    avg_seconds_per_doc: null,
    total_minutes_spent: 0,
    last_completed_at: null,
    eta: null,
    last_error: null,
  },
  {
    source: 'consejo_estado',
    display_name: SOURCE_DISPLAY.consejo_estado,
    total: 200000,
    pending: 200000,
    processing: 0,
    completed: 0,
    failed: 0,
    skipped: 0,
    pct_done: 0,
    avg_seconds_per_doc: null,
    total_minutes_spent: 0,
    last_completed_at: null,
    eta: null,
    last_error: null,
  },
  {
    source: 'dian',
    display_name: SOURCE_DISPLAY.dian,
    total: 15000,
    pending: 15000,
    processing: 0,
    completed: 0,
    failed: 0,
    skipped: 0,
    pct_done: 0,
    avg_seconds_per_doc: null,
    total_minutes_spent: 0,
    last_completed_at: null,
    eta: null,
    last_error: null,
  },
  {
    source: 'jep',
    display_name: SOURCE_DISPLAY.jep,
    total: 2000,
    pending: 2000,
    processing: 0,
    completed: 0,
    failed: 0,
    skipped: 0,
    pct_done: 0,
    avg_seconds_per_doc: null,
    total_minutes_spent: 0,
    last_completed_at: null,
    eta: null,
    last_error: null,
  },
  {
    source: 'datos_gov_co',
    display_name: SOURCE_DISPLAY.datos_gov_co,
    total: 5000,
    pending: 5000,
    processing: 0,
    completed: 0,
    failed: 0,
    skipped: 0,
    pct_done: 0,
    avg_seconds_per_doc: null,
    total_minutes_spent: 0,
    last_completed_at: null,
    eta: null,
    last_error: null,
  },
  {
    source: 'hf_datasets',
    display_name: SOURCE_DISPLAY.hf_datasets,
    total: 1200,
    pending: 1200,
    processing: 0,
    completed: 0,
    failed: 0,
    skipped: 0,
    pct_done: 0,
    avg_seconds_per_doc: null,
    total_minutes_spent: 0,
    last_completed_at: null,
    eta: null,
    last_error: null,
  },
  {
    source: 'repos_universitarios',
    display_name: SOURCE_DISPLAY.repos_universitarios,
    total: 8000,
    pending: 8000,
    processing: 0,
    completed: 0,
    failed: 0,
    skipped: 0,
    pct_done: 0,
    avg_seconds_per_doc: null,
    total_minutes_spent: 0,
    last_completed_at: null,
    eta: null,
    last_error: null,
  },
  {
    source: 'diario_oficial',
    display_name: SOURCE_DISPLAY.diario_oficial,
    total: 50000,
    pending: 50000,
    processing: 0,
    completed: 0,
    failed: 0,
    skipped: 0,
    pct_done: 0,
    avg_seconds_per_doc: null,
    total_minutes_spent: 0,
    last_completed_at: null,
    eta: null,
    last_error: null,
  },
];

export const MOCK_INVENTORY: InventorySummary = {
  total_documents: 128119,
  total_chunks: 982440,
  total_templates: 590,
  total_sentencias: 35200,
  total_normas: 92421,
  postgres_size_mb: 156,
  postgres_limit_mb: 500,
  r2_size_gb: 0.84,
  r2_limit_gb: 10,
  embeddings_cost_usd: 38.7,
  last_updated_at: now(),
  by_source: [
    { source: 'colombia_compra', doc_type: 'contrato_estatal', materia: 'administrativo', count: 40, last_ingested_at: hoursAgo(18) },
    { source: 'defensoria', doc_type: 'cartilla', materia: 'constitucional', count: 198, last_ingested_at: hoursAgo(15) },
    { source: 'icbf', doc_type: 'formato', materia: 'familia', count: 150, last_ingested_at: hoursAgo(14) },
    { source: 'minjusticia', doc_type: 'formato', materia: 'conciliacion', count: 50, last_ingested_at: hoursAgo(14) },
    { source: 'mintrabajo', doc_type: 'modelo', materia: 'laboral', count: 50, last_ingested_at: hoursAgo(13) },
    { source: 'ccb', doc_type: 'minuta', materia: 'comercial', count: 100, last_ingested_at: hoursAgo(12) },
    { source: 'suin_juriscol', doc_type: 'norma', materia: null, count: 87434, last_ingested_at: hoursAgo(8) },
    { source: 'senado', doc_type: 'ley', materia: null, count: 4987, last_ingested_at: hoursAgo(6) },
    { source: 'corte_cc', doc_type: 'sentencia', materia: 'constitucional', count: 35200, last_ingested_at: minutesAgo(2) },
  ],
};

export const MOCK_RUNNING_JOBS: RunningJob[] = [
  {
    job_id: 'job_cc_bulk_w1',
    source: 'corte_cc',
    scheduled_at: hoursAgo(2),
    started_at: hoursAgo(2),
    status: 'running',
    worker_id: 'worker_1',
    current_url: 'https://www.corteconstitucional.gov.co/relatoria/2023/T-156-23.htm',
    progress_pct: 58.7,
    docs_processed: 35200,
    docs_total: 60000,
    errors_count: 295,
    next_retry_at: null,
  },
  {
    job_id: 'job_cc_bulk_w2',
    source: 'corte_cc',
    scheduled_at: hoursAgo(2),
    started_at: hoursAgo(2),
    status: 'running',
    worker_id: 'worker_2',
    current_url: 'https://www.corteconstitucional.gov.co/relatoria/2022/C-401-22.htm',
    progress_pct: 58.7,
    docs_processed: 35200,
    docs_total: 60000,
    errors_count: 295,
    next_retry_at: null,
  },
  {
    job_id: 'job_cc_bulk_w3',
    source: 'corte_cc',
    scheduled_at: hoursAgo(2),
    started_at: hoursAgo(2),
    status: 'running',
    worker_id: 'worker_3',
    current_url: 'https://www.corteconstitucional.gov.co/relatoria/2021/SU-085-21.htm',
    progress_pct: 58.7,
    docs_processed: 35200,
    docs_total: 60000,
    errors_count: 295,
    next_retry_at: null,
  },
];

export const MOCK_CRON_JOBS: CronJob[] = [
  {
    job_id: 'cron_cc_bulk',
    name: 'Corte CC Bulk Ingest',
    source: 'corte_cc',
    cron_expression: '0 2 * * *',
    enabled: true,
    last_run_at: hoursAgo(2),
    next_run_at: new Date(Date.now() + 22 * 3600_000).toISOString(),
    last_status: 'success',
    last_duration_seconds: 5400,
    description: 'Bulk ingest distribuido (1.5h/dia) hasta completar 60K sentencias',
  },
  {
    job_id: 'cron_cc_daily',
    name: 'Corte CC Daily Refresh',
    source: 'corte_cc',
    cron_expression: '0 2 * * *',
    enabled: false,
    last_run_at: null,
    next_run_at: '2026-06-01T07:00:00.000Z',
    last_status: null,
    last_duration_seconds: null,
    description: 'Refresh diario de nuevas sentencias (arranca tras bulk)',
  },
  {
    job_id: 'cron_suin_weekly',
    name: 'SUIN Juriscol Weekly',
    source: 'suin_juriscol',
    cron_expression: '0 3 * * 0',
    enabled: true,
    last_run_at: hoursAgo(72),
    next_run_at: new Date(Date.now() + 4 * 24 * 3600_000).toISOString(),
    last_status: 'success',
    last_duration_seconds: 1820,
    description: 'Refresh semanal de normas via SODA API',
  },
  {
    job_id: 'cron_dian_monthly',
    name: 'DIAN Conceptos Monthly',
    source: 'dian',
    cron_expression: '0 4 1 * *',
    enabled: false,
    last_run_at: null,
    next_run_at: '2026-06-01T09:00:00.000Z',
    last_status: null,
    last_duration_seconds: null,
    description: 'Refresh mensual de conceptos tributarios',
  },
  {
    job_id: 'cron_hf_backup',
    name: 'Hugging Face Backup',
    source: 'system',
    cron_expression: '0 5 * * *',
    enabled: true,
    last_run_at: hoursAgo(15),
    next_run_at: new Date(Date.now() + 9 * 3600_000).toISOString(),
    last_status: 'success',
    last_duration_seconds: 240,
    description: 'Backup nocturno del corpus a HF Datasets',
  },
];

export const MOCK_LOGS: PipelineLogEntry[] = [
  { ts: minutesAgo(0), level: 'info', source: 'corte_cc', job_id: 'job_cc_bulk_w1', message: 'Procesada T-156-23 (15 chunks, 18ms embed)', context: null },
  { ts: minutesAgo(1), level: 'info', source: 'corte_cc', job_id: 'job_cc_bulk_w2', message: 'Procesada C-401-22 (22 chunks, 21ms embed)', context: null },
  { ts: minutesAgo(2), level: 'warn', source: 'corte_cc', job_id: 'job_cc_bulk_w3', message: 'soft_404 detectado en T-999-26, marcado como skipped', context: { url: 'https://www.corteconstitucional.gov.co/relatoria/2026/T-999-26.htm' } },
  { ts: minutesAgo(3), level: 'info', source: 'corte_cc', job_id: 'job_cc_bulk_w1', message: 'Procesada T-155-23 (18 chunks)', context: null },
  { ts: minutesAgo(5), level: 'info', source: 'system', job_id: null, message: 'Storage check: postgres 156MB/500MB (31%), R2 0.84GB/10GB (8.4%)', context: null },
  { ts: minutesAgo(8), level: 'error', source: 'corte_cc', job_id: 'job_cc_bulk_w2', message: 'http_429 rate limited, backoff 60s', context: { retry_after: 60 } },
  { ts: minutesAgo(12), level: 'info', source: 'system', job_id: 'cron_hf_backup', message: 'Backup HF Datasets completado (240s, 0.84GB sincronizado)', context: null },
  { ts: minutesAgo(45), level: 'info', source: 'senado', job_id: 'job_senado_top', message: 'Senado top 5K completado (4987/5000, 13 fallos)', context: null },
  { ts: hoursAgo(6), level: 'warn', source: 'senado', job_id: 'job_senado_top', message: 'parse_error en Ley 1098 de 2006 (Docling failed)', context: { fallback: 'pypdf' } },
  { ts: hoursAgo(8), level: 'info', source: 'suin_juriscol', job_id: 'job_suin_bulk', message: 'SUIN bulk completado: 87434/87437 normas indexadas', context: null },
];
