/* Datos de muestra — caso ficticio + 8 casos realistas CDMX civil/laboral */

const CASES = [
  {
    id: "C-2026-0341",
    cliente: "Mar\u00eda Rodr\u00edguez Vel\u00e1zquez",
    titulo: "Rodr\u00edguez vs. Tel\u00e9fonos de M\u00e9xico",
    materia: "Laboral",
    etapa: "Audiencia preliminar",
    tribunal: "Juzgado 12 Laboral CDMX",
    expediente: "473/2026",
    proxima: "Mi\u00e9 27 mayo \u00b7 10:00",
    proximaTipo: "Audiencia oral",
    diasRestantes: 3,
    owner: "Lic. Ana \u00c1lvarez",
    prioridad: "alta",
    pendientes: 2,
    docs: 14,
    ultimo: "Hace 12 min",
  },
  {
    id: "C-2026-0298",
    cliente: "Constructora del Valle SA de CV",
    titulo: "Constructora del Valle vs. Inmobiliaria Reforma",
    materia: "Civil",
    etapa: "Contestaci\u00f3n",
    tribunal: "Juzgado 38 Civil CDMX",
    expediente: "1284/2025",
    proxima: "Vie 29 mayo \u00b7 13:30",
    proximaTipo: "Vencimiento",
    diasRestantes: 5,
    owner: "Lic. Ana \u00c1lvarez",
    prioridad: "alta",
    pendientes: 1,
    docs: 28,
    ultimo: "Ayer",
  },
  {
    id: "C-2026-0287",
    cliente: "Jos\u00e9 Luis Hern\u00e1ndez",
    titulo: "Hern\u00e1ndez vs. Grupo Bimbo",
    materia: "Laboral",
    etapa: "Conciliaci\u00f3n",
    tribunal: "CFCRL CDMX",
    expediente: "C/89/2026",
    proxima: "Lun 1 jun \u00b7 09:00",
    proximaTipo: "Audiencia conc.",
    diasRestantes: 8,
    owner: "Lic. Carlos M\u00e9ndez",
    prioridad: "media",
    pendientes: 3,
    docs: 9,
    ultimo: "Hace 2 d\u00edas",
  },
  {
    id: "C-2026-0263",
    cliente: "Patricia Ju\u00e1rez M\u00e9ndez",
    titulo: "Ju\u00e1rez vs. Banco Santander M\u00e9xico",
    materia: "Civil",
    etapa: "Pruebas",
    tribunal: "Juzgado 51 Civil CDMX",
    expediente: "0892/2025",
    proxima: "Mar 9 jun",
    proximaTipo: "Desahogo prueba",
    diasRestantes: 16,
    owner: "Lic. Ana \u00c1lvarez",
    prioridad: "media",
    pendientes: 0,
    docs: 22,
    ultimo: "Hace 4 d\u00edas",
  },
  {
    id: "C-2026-0241",
    cliente: "Roberto Aguilar S\u00e1nchez",
    titulo: "Aguilar vs. Aerom\u00e9xico",
    materia: "Laboral",
    etapa: "Demanda",
    tribunal: "Juzgado 7 Laboral CDMX",
    expediente: "Pendiente",
    proxima: "Borrador",
    proximaTipo: "Drafting",
    diasRestantes: null,
    owner: "Lic. Ana \u00c1lvarez",
    prioridad: "media",
    pendientes: 1,
    docs: 4,
    ultimo: "Hace 1 hora",
  },
  {
    id: "C-2026-0218",
    cliente: "Distribuidora Norte SA",
    titulo: "Distribuidora Norte vs. Comercial M\u00e9xico",
    materia: "Mercantil",
    etapa: "Sentencia",
    tribunal: "Juzgado 4 Mercantil CDMX",
    expediente: "0418/2024",
    proxima: "12 jun",
    proximaTipo: "Notificaci\u00f3n",
    diasRestantes: 19,
    owner: "Lic. Carlos M\u00e9ndez",
    prioridad: "baja",
    pendientes: 0,
    docs: 41,
    ultimo: "Hace 1 sem",
  },
  {
    id: "C-2026-0192",
    cliente: "Lucia Ram\u00edrez Torres",
    titulo: "Ram\u00edrez vs. IMSS",
    materia: "Amparo",
    etapa: "Suspensi\u00f3n",
    tribunal: "Juzgado 5 Distrito CDMX",
    expediente: "234/2026",
    proxima: "16 jun",
    proximaTipo: "Audiencia const.",
    diasRestantes: 23,
    owner: "Lic. Ana \u00c1lvarez",
    prioridad: "alta",
    pendientes: 2,
    docs: 17,
    ultimo: "Hace 3 d\u00edas",
  },
  {
    id: "C-2026-0177",
    cliente: "Editorial Letras SA",
    titulo: "Editorial Letras vs. Quevedo (regal\u00edas)",
    materia: "Civil",
    etapa: "Demanda",
    tribunal: "Juzgado 22 Civil CDMX",
    expediente: "1102/2026",
    proxima: "20 jun",
    proximaTipo: "Emplazamiento",
    diasRestantes: 27,
    owner: "Lic. Ana \u00c1lvarez",
    prioridad: "baja",
    pendientes: 1,
    docs: 6,
    ultimo: "Hace 1 sem",
  },
];

const TESIS = [
  {
    registro: "2027183",
    rubro: "DESPIDO INJUSTIFICADO. PROCEDE EL PAGO DE INDEMNIZACI\u00d3N CONSTITUCIONAL CUANDO EL PATR\u00d3N NO ACREDITA LA CAUSA INVOCADA.",
    instancia: "Segunda Sala",
    epoca: "Und\u00e9cima \u00c9poca",
    tipo: "Jurisprudencia 2a./J. 14/2024",
    relevancia: "Muy alta",
    vigencia: "vigente",
    fragmento: "Cuando el patr\u00f3n invoca causal de despido sin acreditar los hechos constitutivos de la falta, procede el pago de tres meses de salario a t\u00edtulo de indemnizaci\u00f3n constitucional\u2026",
  },
  {
    registro: "2026891",
    rubro: "PRIMA DE ANTIG\u00dcEDAD. C\u00c1LCULO CON SALARIO TOPADO A DOS VECES EL SALARIO M\u00cdNIMO GENERAL VIGENTE.",
    instancia: "Cuarta Sala",
    epoca: "Und\u00e9cima \u00c9poca",
    tipo: "Tesis aislada IV.4o.T.21 L (11a.)",
    relevancia: "Alta",
    vigencia: "vigente",
    fragmento: "El art\u00edculo 162 de la LFT establece que la prima de antig\u00fcedad se calcular\u00e1 con base en doce d\u00edas de salario por cada a\u00f1o de servicio, topado a dos veces el SMGV\u2026",
  },
  {
    registro: "2025104",
    rubro: "SALARIOS CA\u00cdDOS. L\u00cdMITE TEMPORAL DE DOCE MESES CONFORME A LA REFORMA DE 2012.",
    instancia: "Segunda Sala",
    epoca: "D\u00e9cima \u00c9poca",
    tipo: "Jurisprudencia 2a./J. 89/2023",
    relevancia: "Alta",
    vigencia: "vigente",
    fragmento: "La reforma del art\u00edculo 48 de la LFT estableci\u00f3 un tope de doce meses para el c\u00e1lculo de salarios ca\u00eddos, m\u00e1s intereses\u2026",
  },
  {
    registro: "2024417",
    rubro: "CARGA DE LA PRUEBA EN DESPIDO INJUSTIFICADO. CORRESPONDE AL PATR\u00d3N CONFORME AL ART\u00cdCULO 784 DE LA LFT.",
    instancia: "Segunda Sala",
    epoca: "D\u00e9cima \u00c9poca",
    tipo: "Jurisprudencia 2a./J. 76/2022",
    relevancia: "Muy alta",
    vigencia: "vigente",
    fragmento: "La carga procesal de demostrar la justificaci\u00f3n del despido recae en el patr\u00f3n, sin que la sola negativa del trabajador releve al primero\u2026",
  },
];

const TOOLS_RUNNING = [
  {id:"t1", name:"research_jurisprudence", label:"Buscar jurisprudencia SCJN", status:"done", time:"1.2s", result:"4 tesis"},
  {id:"t2", name:"validate_citation", label:"Verificar citas vs registry", status:"done", time:"0.4s", result:"4/4 \u2713"},
  {id:"t3", name:"calc_liquidation", label:"Calcular prestaciones LFT", status:"done", time:"0.2s", result:"$432,180 MXN"},
  {id:"t4", name:"load_template", label:"Cargar plantilla demanda laboral", status:"done", time:"0.1s", result:"v3.2"},
  {id:"t5", name:"draft_pleading", label:"Redactar promoci\u00f3n", status:"running", time:"3.8s", result:""},
  {id:"t6", name:"verify_dates", label:"Validar plazos procesales", status:"queued", time:"\u2014", result:""},
];

const NSM = {
  documentosMes: 47,
  documentosTarget: 40,
  voiceCommands: 89,
  retention: 72,
  ahorroHoras: 31,
};

Object.assign(window, { CASES, TESIS, TOOLS_RUNNING, NSM });
